added build and push to ecr

diff --git a/.github/workflows/netflix.yml b/.github/workflows/netflix.yml
--- a/.github/workflows/netflix.yml
+++ b/.github/workflows/netflix.yml
@@ -12,6 +12,7 @@ on:
 
 env:
   AWS_REGION: us-east-1
+  ECR_REPOSITORY: neflix-clone
 
 jobs:
   Code-Quality-checks:
@@ -79,3 +80,67 @@ jobs:
           scan-type: "fs"
           scan-ref: "."
           output: "trivyfs.txt"
+          severity: "HIGH,CRITICAL"
+          exit-code: "0" # Do not fail build
+          format: "table"
+
+      - name: Upload Trivy FS Scan Report
+        uses: actions/upload-artifact@v4
+        with:
+          name: trivy-fs-scan
+          path: trivyfs.txt
+
+  build-and-push:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
+
+      - name: Configure AWS Credentials
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          role-to-assume: ${{ secrets.AWS_GITHUB_ROLE }}
+          aws-region: ${{ env.AWS_REGION }}
+
+      - name: Login to Amazon ECR
+        id: login-ecr
+        uses: aws-actions/amazon-ecr-login@v2
+
+      - name: Get version from VERSION file
+        id: get-version
+        run: |
+          if [ -f VERSION ]; then
+            VERSION=$(cat VERSION)
+          else
+            echo "VERSION file not found. Exiting..."
+            exit 1
+          fi
+          echo "Current version: $VERSION"
+          echo version=$VERSION >> $GITHUB_OUTPUT
+
+      - name: Build Docker image
+        run: |
+          docker build -t ${{ env.ECR_REPOSITORY }}:${{ steps.get-version.outputs.version }} ./client
+
+      - name: Scan image with Trivy
+        uses: aquasecurity/trivy-action@master
+        with:
+          image-ref: ${{ env.ECR_REPOSITORY }}:${{ steps.get-version.outputs.version }}
+          format: "table"
+          severity: CRITICAL,HIGH
+          ignore-unfixed: true
+          exit-code: 1 # fail if vulnerabilities are found
+
+      - name: Tag and Push Docker image
+        run: |
+          docker tag ${{ env.ECR_REPOSITORY }}:${{ steps.get-version.outputs.version }} \
+            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ steps.get-version.outputs.version }}
+
+          docker tag ${{ env.ECR_REPOSITORY }}:${{ steps.get-version.outputs.version }} \
+            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest
+
+          docker push ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ steps.get-version.outputs.version }}
+          docker push ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest
